workflows:
  ios-release:
    name: iOS Release Workflow
    max_build_duration: 60
    platform: ios
    flutter: stable
    ios:
      build_mode: release
      output_dir: build/ios/iphoneos
      ipa:
        distribution_method: ad-hoc  # O 'app-store' si lo subes a la App Store
        signing:
          certificate: 'Apple Distribution'
          provisioning_profile: 'path_to_your_provisioning_profile'
    dependencies:
      cache:
        directories:
          - $HOME/.pub-cache
          - $HOME/ios/Pods
    scripts:
      - name: Clean Flutter project
        script: flutter clean
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      - name: Run Flutter app for iOS
        script: flutter run --release --no-sound-null-safety
    artifacts:
      - build/ios/iphoneos/*.ipa
