workflows:
  ios-release:
    name: iOS Release Workflow
    max_build_duration: 60
    platform: ios
    flutter: stable
    ios:
      build_mode: release
      output_dir: build/ios/iphoneos
      ipa:
        distribution_method: ad-hoc  # O 'app-store' si lo subes a la App Store
        signing:
          certificate: 'Apple Distribution'
          provisioning_profile: 'path_to_your_provisioning_profile'
    artifacts:
      - build/ios/iphoneos/*.ipa
